---
- name: Pull Docker Image
  hosts: all
  tasks:
    - name: Pull Calculator Image from Docker Hub
      docker_image:
        name: revanth321/spe
        source: pull
    - name: running container
      shell: docker run -it -d revanth321/spe /bin/bash